version: 2

models:
  - name: regions
    columns:
    - name: R_REGIONKEY
      tests: 
        # Should not contain null values.
        - not_null
        # Should be unique
        - unique
    - name: R_NAME
      tests:
        # Should be either 'free_parking' or 'paid_parking'.
        - accepted_values:
            values: ['AFRICA','AMERICA','ASIA','EUROPE','MIDDLE EAST']