WITH REGIONS AS 
(
SELECT * 
 FROM {{ref('regions')}}
WHERE R_REGIONKEY IN (0,1)
),
NATIONS AS 
(
SELECT * 
FROM {{ref('nations')}}
WHERE N_REGIONKEY BETWEEN 1 AND 15
)
SELECT R_NAME,COUNT(*) AS NUMBER_OF_COUNTRIES
FROM REGIONS JOIN NATIONS 
ON REGIONS.R_REGIONKEY=NATIONS.N_REGIONKEY
GROUP BY R_NAME